<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ColoredTree" nsURI="ColoredTree" nsPrefix="ct">
  <eClassifiers xsi:type="ecore:EClass" name="ColoredTree" eSuperTypes="platform:/resource/example/Trees.ecore#//Tree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="RED" value="1"/>
    <eLiterals name="GREEN" value="2"/>
    <eLiterals name="BLUE" value="3"/>
  </eClassifiers>
</ecore:EPackage>
